import React from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import ScreenHeader from './ScreenHeader';

export const metricPalette = { bg: '#F9F5FF', surface: '#FFF', low: '#F2EFFF', primary: '#0846ED', primaryFaint: 'rgba(8,70,237,.10)', tertiary: '#913983', tertiaryFaint: 'rgba(145,57,131,.10)', success: '#16A34A', successFaint: '#E7F6EC', warning: '#D97706', warningFaint: 'rgba(217,119,6,.12)', text: '#2B2A51', muted: '#585781', border: 'rgba(171,169,215,.35)' };
export const money = (value, currency = 'ARS') => `${currency} ${Number(value || 0).toLocaleString('es-AR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export const moneyMap = (values = {}) => Object.keys(values).length ? Object.entries(values).map(([c, v]) => money(v, c)).join('  ') : money(0);
export function MetricScreen({ navigation, route, title, refreshing, onRefresh, children }) { return <View style={s.screen}><ScreenHeader navigation={navigation} route={route} title={title} onBackPress={() => navigation.navigate('Perfil')} /><ScrollView contentContainerStyle={s.body} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}>{children}</ScrollView></View>; }
export function MetricHero({ icon, eyebrow, title, value, tone = 'primary' }) { const color = metricPalette[tone] || metricPalette.primary; return <View style={s.hero}><View style={[s.heroIcon, { backgroundColor: metricPalette[`${tone}Faint`] || metricPalette.primaryFaint }]}><MaterialIcons name={icon} size={24} color={color} /></View><Text style={s.eyebrow}>{eyebrow}</Text><Text style={s.heroTitle}>{title}</Text><Text style={[s.heroValue, { color }]}>{value}</Text></View>; }
export const SummaryCard = ({ children }) => <View style={s.card}>{children}</View>;
export const Section = ({ title, children }) => <View style={s.card}><Text style={s.sectionTitle}>{title}</Text>{children}</View>;
export const MetricRow = ({ label, value }) => <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>;
export function MetricTag({ label, tone = 'primary' }) { const color = metricPalette[tone] || metricPalette.primary; return <View style={[s.tag, { backgroundColor: metricPalette[`${tone}Faint`] || metricPalette.primaryFaint }]}><Text style={[s.tagText, { color }]}>{label}</Text></View>; }
export const MetricItem = ({ children }) => <View style={s.item}>{children}</View>;
export function ViewAllButton({ expanded, total, onPress }) { if (total <= 3) return null; return <TouchableOpacity style={s.more} onPress={onPress}><Text style={s.moreText}>{expanded ? 'Ver menos' : 'Ver todas'}</Text><MaterialIcons name={expanded ? 'expand-less' : 'chevron-right'} size={18} color={metricPalette.primary} /></TouchableOpacity>; }
export const EmptyMetric = ({ icon, title, text }) => <View style={s.empty}><View style={s.heroIcon}><MaterialIcons name={icon} size={24} color={metricPalette.primary} /></View><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyText}>{text}</Text></View>;
export function CategoryBreakdown({ values = {} }) { const entries = Object.entries(values); return entries.length ? <Section title="Por categoría">{entries.map(([name, value]) => <MetricRow key={name} label={name.replace(/_/g, ' ')} value={value} />)}</Section> : null; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: metricPalette.bg }, body: { padding: 20, paddingBottom: 40 }, hero: { marginBottom: 16 }, heroIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: metricPalette.primaryFaint, alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, eyebrow: { color: metricPalette.primary, fontSize: 11, fontWeight: '900', letterSpacing: 1.3, textTransform: 'uppercase', marginBottom: 6 }, heroTitle: { color: metricPalette.text, fontSize: 34, fontWeight: '900' }, heroValue: { fontSize: 42, fontWeight: '900', marginTop: 8 }, card: { backgroundColor: metricPalette.surface, borderRadius: 16, borderWidth: 1, borderColor: metricPalette.border, padding: 17, marginBottom: 14 }, sectionTitle: { color: metricPalette.text, fontSize: 16, fontWeight: '900', marginBottom: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 16, paddingVertical: 8 }, rowLabel: { flex: 1, color: metricPalette.muted, fontSize: 13, fontWeight: '700' }, rowValue: { flexShrink: 1, color: metricPalette.text, fontSize: 14, fontWeight: '900', textAlign: 'right' }, tag: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4 }, tagText: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase' }, item: { borderTopWidth: 1, borderTopColor: metricPalette.border, paddingTop: 12, marginTop: 12 }, more: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: metricPalette.primary, borderRadius: 12, padding: 10, marginTop: 14 }, moreText: { color: metricPalette.primary, fontWeight: '900' }, empty: { backgroundColor: metricPalette.surface, borderRadius: 16, borderWidth: 1, borderColor: metricPalette.border, padding: 24, alignItems: 'center' }, emptyTitle: { color: metricPalette.text, fontSize: 17, fontWeight: '900' }, emptyText: { color: metricPalette.muted, fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 6 } });
